// Tooltip glossary for every key-value in the terminal. Generated from the
// UI audit (see UI-AUDIT.md) and hand-checked against PLAN.md + lib/svi.ts.
// Keyed by a stable id; LabelTip looks the copy up by key (falling back to the
// literal string if the key is unknown), so a label and its definition stay in
// one place. Plain-English first, then the precise clause with units/formula.

export const GLOSSARY: Record<string, string> = {
  // — IV surface —
  "arb-free": "The vol shape leaves no risk-free money on the table. Green when all no-arb checks pass: calendar (total variance non-decreasing in T) AND butterfly (Durrleman g(k)>=0 across the k-grid).",
  "atm-term-overlay": "At-the-money implied vol at the nearest expiry vs the farthest, i.e. the term-structure of ATM vol. frontIV=rows[0].atmIV, backIV=rows[last].atmIV; arrow reads near->far, rendered as integer %.",
  "butterfly-arb": "Butterfly arbitrage: a smile shaped so a butterfly spread costs negative (negative implied density). Red when Durrleman g(k)=(1-k*w'/2w)^2 -(w'^2/4)(1/w+1/4) +w''/2 goes negative for any sampled k.",
  "calendar-arb": "Calendar arbitrage: a longer-dated expiry is priced with less total variance than a shorter one at the same strike, which should be impossible. Red when w_{T+1}(k) < w_T(k) for any sampled k over kMin..kMax.",
  "iv-heat-legend": "Color key: the surface's color encodes implied vol, dark blue = lowest vol on screen, bright cyan/white = highest. The ramp maps NORMALIZED IV in [0,1] across the current surface, not an absolute vol scale.",
  "iv-surface-panel": "3-D map of how BTC option-implied volatility varies by strike and time-to-expiry. Stacks per-expiry SVI smiles into a (k,T)->IV surface; IV(k)=sqrt(w(k)/T), w(k)=a+b(rho(k-m)+sqrt((k-m)^2+sigma^2)).",
  "moneyness-readout": "How far the cursor's strike sits above (+) or below (-) the forward, in percent. (exp(k)-1)*100 where k=log-moneyness; k=0 is at-the-money. Note ticks labeled +/-10/20% are LOG-moneyness, so +/-0.2 ~ -18%..+22% actual.",
  "surface-iv-readout": "Implied volatility at the point under your cursor, the headline value. iv = min(sqrt(w/T), 1.0) at the snapped real tenor; an annualized vol fraction shown x100 to 1 decimal.",
  "svi-model": "Stochastic-Volatility-Inspired model (Gatheral & Jacquier 2014) that fits the whole vol smile with five numbers. Parameterizes total variance w(k)=a+b(rho(k-m)+sqrt((k-m)^2+sigma^2)) vs log-moneyness k.",
  "real-vs-interp-ribs": "Bright grid lines are real on-chain expiries; dimmer lines are smooth fill between them. Interp ribs multiply color by 0.42 and are built in total-variance space (linear in T) to stay calendar-arb-free.",
  "strike-axis-hint": "Axis hint: moving right raises the option strike. Columns span log-moneyness k=-0.2..0.2 (~ -18% to +22% of forward); no numeric strike ticks are drawn.",
  "surface-height": "How tall a point rises = relatively higher IV on this surface. y=norm*Y_SCALE where norm=(iv-ivMin)/span; height is normalized across the whole surface to fill the frame, not an absolute IV height.",
  "tenor-countdown": "Live countdown to an expiry. fmtDuration(expiry-now): Dd Hh / Hh MMm / Mm SSs / Ss, or 'expired' if <=0. Nearest tenor highlighted cerulean; hovered tenor underlined.",
  "tick-pulse": "The wireframe briefly brightens when a fresh on-chain SVI update arrives, signaling the desk is live. On version change (checksum of SVI data) wire opacity ramps 0.8->0.5 over 700ms.",
  "drag-to-orbit": "Interaction hint: drag to rotate the camera around the surface. Camera-only orbit, damped, no pan/zoom, polar angle clamped; auto-rotates while not hovering.",
  "n-tenors": "How many distinct real on-chain expiries are stacked into the surface right now. Count of active oracle tenors with valid SVI and T>0; interpolated fill-ribs between them are not counted.",
  "surface-resolving": "The surface is still loading. Shown until at least two expiries have data, since buildSurface needs >=2 tenors to render a surface.",
  "tenor-axis": "Time-to-expiry axis along the surface's depth. Each entry is the live countdown to one real oracle expiry; the nearest tenor sits closest to the camera and the structure recedes as T grows.",
  // — Smile / skew —
  "atm-iv": "At-the-money implied volatility: the market's expected annualized BTC swing, the single most-watched vol number. atmIV=impliedVol(0,p,T)=sqrt(w(0)/T)*100; live BTC ~42-45%. Also sizes the vault stress shock.",
  "call-wing": "Implied vol 10% above the forward (upside/call wing) = how expensive upside bets are. impliedVol(+0.1, p, T)*100, strike ~10% over forward; 1 dp.",
  "fly": "Butterfly: how much the wings curve up vs the at-the-money point, a measure of smile convexity. fly=(put+call)/2 - atm in IV points; positive = wings richer than ATM; fmtSigned 1 dp.",
  "put-wing": "Implied vol 10% below the forward (downside/put wing) = how expensive crash protection is. impliedVol(-0.1, p, T)*100, strike ~10% under forward; 1 dp.",
  "skew-rr": "Risk reversal: how much pricier downside is than upside (put - call IV at +/-10% moneyness). Negative = market paying up for crash protection (put skew, normal for BTC); fmtSigned 1 dp, warn tone when <0.",
  "histogram-axis": "OI chart x-axis: strike distance below spot (left), ATM at center, strike distance above (right). reach=max(0.005,max|mny|)*1.25; span is symmetric and adaptive so near-ATM strikes stay legible.",
  "histogram-hover": "Hovering an OI bar shows that strike's price, its distance from spot in %, and the Up vs Dn position counts. fmtPrice(strike), fmtMny(strike/spot-1) signed, then raw up/dn counts.",
  "live-replay": "Live = newest on-chain smile; Replay = a scrubbed past snapshot stamped with its UTC capture time. Replay pill (warn tone) shows utcClock(snapshot.checkpoint_timestamp_ms) when you scrub back in history.",
  "oi-by-strike": "Open interest grouped by strike: how many live binary positions sit at each strike, aligned under the smile. PositionMinted grouped by strike (filtered to |strike/spot-1|<=0.5); bars = up+dn count per strike.",
  "smile-hover": "Hovering the smile shows IV and moneyness at the cursor. (iv*100) to 1 dp in accent + signed (k*100) in faint; snaps to nearest of 80 sampled points.",
  "smile-panel": "One expiry's vol smile: how IV changes across strikes and whether it tilts toward puts or calls. Plots IV(k)=sqrt(w(k)/T) from the live SVI fit, with skew/fly readouts; k=ln(K/F).",
  "smile-x-ticks": "Smile chart x-axis: deep-put edge at -30% moneyness (left), ATM (center, strike=forward), deep-call edge at +30% (right). Endpoints are SMILE_OPTS kMin/kMax = -0.3/+0.3.",
  "smile-y-tick": "Top of the IV scale on the smile chart = highest vol shown. (max(iv)+12% pad)*100, top-left. Only the high end is labeled; the low end has no numeric tick.",
  "time-travel": "Scrubber to replay how this expiry's smile evolved over past SVI updates. Slider 0..liveIdx over the SVI history array (shown only when >1 snapshot); pushing to liveIdx returns to live.",
  "up-dn-legend": "Color key for binary direction: green Up bets the price ends above strike, red Dn bets it ends below. In the OI histogram each bar is a stacked green-over-red split (upFrac=up/(up+dn)).",
  "jump-to-live": "Resets the replay scrubber to the newest live smile. Faint 'Live' when already live; accent '-> Jump to live' when scrubbed back (sets scrub=null).",
  "smile-states": "Status messages: no oracle selected, feed failed, or this expiry already settled (status=settled or T<=0) so there is no live curve. Settled still shows the arb verdict on the last fitted params.",
  // — Oracle state (SVI params) —
  "atm-var": "Total variance at-the-money, the raw un-annualized quantity ATM IV derives from; near-zero for short expiries. atmVar=totalVariance(0,p)=a+b(rho(-m)+hypot(-m,sigma)); shown toExponential(2). IV=sqrt(var/T).",
  "checkpoint": "The Sui checkpoint (block-height-like sequence number) this snapshot came from, proof of freshness. ~9-11 digit monotonic ledger height, shown with thousands separators.",
  "expiry": "Time left until this contract settles (or 'Settled' once done). fmtDuration(expiry-now); drives the time-to-expiry T used in IV(k)=sqrt(w(k)/T); <=0 renders 'expired'.",
  "forward": "The price the market expects BTC to have at this option's expiry, the reference the whole smile is centered on. latest_price.forward, 1e9-scaled $; F is the denominator in k=ln(K/F).",
  "oracle-panel": "The live on-chain oracle: current price plus the five SVI numbers that define BTC's whole implied-vol smile. Data from GET /oracles/:id/state (meta + latest_price + latest_svi).",
  "strike-matrix-ticks": "Strike positions as percent moneyness, ATM in the middle. Labels read like +/-10/20% but k is LOG-moneyness (k=ln(K/F)), so -0.2 is really ~-18% actual strike offset.",
  "svi-a": "SVI level: the baseline floor of total variance that shifts the whole smile up or down. Raw-SVI a in w(k)=a+b(...); decoded as on-chain raw.a/1e9, shown toExponential(3) e.g. 2.767e-5.",
  "svi-b": "SVI slope: how steep the smile's wings are, i.e. the angle between its two asymptotes. Raw-SVI b>=0; decoded raw.b/1e9, shown toExponential(3) e.g. 4.037e-4.",
  "svi-m": "SVI shift: horizontal position of the smile's low point relative to at-the-money. m = log-moneyness of the vertex shift = (raw.m/1e9)*sign; w(k) centers on (k-m); shown toFixed(5).",
  "svi-rho": "SVI skew/tilt: negative means downside (put) strikes carry richer vol, the usual fear premium. rho in [-1,1] = (raw.rho/1e9)*sign; live BTC ~ -0.94 (steep put skew); shown toFixed(4), tinted warn when <0.",
  "svi-sigma": "SVI curvature: how rounded vs sharp the bottom of the smile is (small=sharp V, large=gentle bowl). sigma>0 = raw.sigma/1e9, enters as hypot(k-m, sigma); shown toFixed(5). Unrelated to the stress sigma.",
  "term-structure": "How ATM vol changes across expiries, showing an upward or inverted curve. Readout = nearest atmIV% -> farthest atmIV% over the active oracles, each impliedVol(0,params,T)*100; tenor labels are the near/far countdowns.",
  "feed-age": "How many seconds ago the oracle last updated, the panel's freshness verdict. ageS=round((now-checkpoint_ts)/1000), rendered '^ Ns ago'; green if <120s, warn otherwise.",
  "oracle-status": "Whether this expiry is still trading, has settled, or was just created. Derived server-side: settled_at->settled (neutral), else activated_at->active (green), else created (warn).",
  "vol-by-strike": "A row of IV readings across strikes showing how vol rises out-of-the-money (the skew). Each cell = impliedVol(k,p,T)*100 rounded to integer % over k=[-0.2,-0.1,0,0.1,0.2].",
  "oracle-id": "The on-chain object ID of this oracle, shortened for explorer lookup. truncateAddr(oracle_id, 6, 4) -> '0x8263...d6cf'; one oracle = one rolling expiry.",
  "spot": "Current BTC price the oracle reports, the headline number this panel verdicts on. latest_price.spot, 1e9-scaled via fmtPrice to '$69,315' (0 dp); per-digit pop on tick.",
  "spot-sparkline": "Mini trend of recent spot prices with the % move over the window, green up / red down. spotChange=(last-first)/first*100 over the spot-history samples; fmtSigned 2 dp.",
  // — Vault / PLP risk —
  "apy": "Annualized LP return over the vault's recorded history, projected to a full year. ((last.share_price/first.share_price - 1)/years)*100, simple non-compounded over the perf window; green when positive, null if <2 points.",
  "available-liq": "Free capital the vault can pay out or let LPs withdraw right now = funds not reserved against max payout. data.available_liquidity, 1e6-scaled; the numerator of the stress buffer.",
  "lp-net-flow": "Whether LPs are net depositing into or withdrawing from the vault. Running cumulative sum of supplies (+) minus withdrawals (-) over /lp/*; the sparkline plots that series. Counts: N up deposits, M down withdrawals, net dUSDC in.",
  "max-payout": "The largest total the vault could owe if every open position pays out fully, a hard liability ceiling (Predict payouts are capped). data.total_max_payout, 1e6-scaled, warn tone; denominator of max-payout-util and the stress model.",
  "max-payout-util": "Tail-risk gauge: how close the worst-case total payout is to exhausting the vault. max_payout_utilization = total_max_payout / capacity, 0..1 shown x100 to 2 dp; warn-tone meter (the LP-safety tail metric).",
  "modeled-payout": "The dUSDC the vault is modeled to owe traders in this crash. stressedPayout = maxPayout*payoutFrac, payoutFrac = mtmFrac+(1-mtmFrac)(1-e^(-sigma/2.5)) ramping to the cap as sigma grows. Heuristic, not position-level pricing.",
  "plp-share-price": "What one PLP vault share is worth now; above $1.0000 means LPs are in profit. share_price=vault_value/plp_total_supply, starts at 1.0 at inception; header shows 4 dp, the perf chart plots its time series.",
  "plp-supply": "Total PLP shares outstanding across all LPs. data.plp_total_supply, 1e6-scaled (rendered like a $ figure though it's a share count); vault_value / plp_total_supply = share price.",
  "sigma-move": "How far BTC would drop in the simulated 1-day N-sigma crash (downside only). -(moveFrac*100), moveFrac = atmIV*sqrt(1/365.25)*sigma; warn tone.",
  "stress-ladder": "Table previewing crash size and coverage at fixed 1/2/3/5 sigma. Move = modeled -% drop, Buffer = availLiq/(maxPayout*payoutFrac) coverage multiple; color safe >=2, warn >=1, breach <1.",
  "stress-sigma": "Number of standard deviations in the modeled 1-day BTC move; bigger = rarer, more extreme crash. moveFrac = atmIV*sqrt(1/365.25)*sigma. Unrelated to the SVI sigma curvature param.",
  "stress-verdict": "Headline: would the vault survive an N-sigma 1-day crash? buffer = availLiq/stressedPayout; 'Survives Nsigma . Xx buffer' (safe >=2, warn >=1) or 'Breach' when buffer<1. The flagship LP-safety verdict.",
  "stressed-spot": "Where BTC's price would land after the simulated crash. stressedSpot = spot*(1-moveFrac), 1e9-scaled, 0 dp; shown only when spot is known.",
  "total-mtm": "Mark-to-market: the current net value of all open positions the vault holds against traders. data.total_mtm, 1e6-scaled; feeds the stress model's mtmFrac=clamp(mtm/maxPayout,0..1).",
  "utilization": "How much of the vault's capital is currently tied up backing open positions. data.utilization, a 0..1 fraction shown x100 to 2 dp; meter fills value*100%.",
  "vault-value": "Total mark-to-market worth of the vault's assets right now. data.vault_value (quote balance adjusted for open-position MtM), 1e6-scaled, fmtUsdCompact e.g. $1.01M. Distinct from raw cash vault_balance.",
  "dusdc": "Predict's testnet-only quote stablecoin (NOT official testnet USDC). All vault USD figures are dUSDC amounts scaled by 1e6.",
  "net-deposits": "Lifetime LP money put in minus taken out = the cost basis of LP capital; compare to vault value to read aggregate LP PnL. data.net_deposits = total_supplied - total_withdrawn, 1e6-scaled.",
  "sparkline": "A tiny axis-less trend line: left end is the start of the window, right end is now; y normalized to the series min/max. Renders only with >=2 points; pure shape, stroke = accent-brand.",
  "stress-available": "Free vault capital available to absorb the modeled payout = data.available_liquidity (1e6-scaled, safe tone). The numerator of buffer = availLiq/stressedPayout.",
  "stress-slider": "Drag to choose crash severity, 0 to 6 standard deviations (step 0.5, default 5). Drives the modeled move, stressed spot, payout and buffer; readout shows sigma to 1 dp.",
  "supplied": "All dUSDC ever deposited into the vault by LPs. data.total_supplied, 1e6-scaled, green tone.",
  "vault-panel": "Answers 'is it safe for liquidity providers to underwrite this market?'. The PLP (Predict Liquidity Pool) is the pooled dUSDC that takes the other side of every binary trade.",
  "withdrawn": "All dUSDC ever pulled out of the vault by LPs. data.total_withdrawn, 1e6-scaled, dim tone.",
  "perf-chart": "Area chart of PLP share price over time (lightweight-charts), right price-axis at 4-dp precision (minMove 0.0001). Hover shows exact share price (4 dp) + the date for that point.",
  // — Desk (live flow / settle) —
  "flow-amount": "Row amount, one column overloaded by sign+color: -$cost = premium paid to open (mint, dim); +$payout = winning settle (redeem, green); $0.00 = position expired worthless (loss, faint). 2 dp, U+2212 minus.",
  "flow-columns": "Feed columns: Time = UTC HH:MM:SS the event hit chain (newest first); Side = UP/DN direction; Strike = settle price level (1e9-scaled $); Prem/payout = premium out (mint, -) or payout in (redeem, +).",
  "taker-win": "Share of settled bets where the trader won money; under 50% means the PLP vault has the edge. winRate = wins/total*100 (wins = settled with payout>0); green when <50%, amber when >=50%.",
  "up-dn-bar": "Green-for-UP / red-for-DN bar showing the share of recent bets that are bullish vs bearish. upPct = upCount/mints*100, count-weighted (not premium-weighted); defaults to 50% when no mints.",
  "updn-win-split": "Win-rate split: how often bullish vs bearish bets won among settled positions. upWinRate/dnWinRate = wins/count*100 within each subset; a big asymmetry hints at directional mispricing of UP vs DN binaries.",
  "flow-side-glyph": "Per-row direction: green UP^ (binary call, wins if settle >= strike) or red DN v (binary put, wins if settle < strike). Maps FlowItem.isUp.",
  "payouts": "Total dollars paid to winning takers across all settled positions = the vault's gross loss to traders. Sum of PositionRedeemed.payout over wins only (payout>0), 1e6-scaled.",
  "positioning": "Crowd sentiment over the last N opened positions, i.e. which way recent traders are betting. N = count of mint FlowItems in the window; redeems excluded; this is order-flow direction, not settled outcomes.",
  "row-mine": "A faint blue tint marks trades from your connected wallet. Applied when your account address == the mint trader / redeem owner; requires a connected Sui wallet.",
  "settlement-count": "How many positions have actually settled in the redeemed feed. N = count of redeemed positions with is_settled=true; the block renders only when N>0.",
  "vol-premium": "Total premium paid to open all recent positions in the window. Sum of mint cost (raw 1e6 dUSDC) -> fmtUsdCompact e.g. $12.3K. This is premium spent, NOT notional or payout exposure.",
  "desk-panel": "The 'can I act on it?' room: a live merged feed of position mints (order flow) and redeems (settlements) plus aggregate positioning and settlement stats. Polls /positions/minted and /redeemed every 6s.",
  "flow-event-count": "How many recent trade events are loaded in the feed (capped at 80). Merged mint+redeem FlowItems, sorted newest-first; shows 'Live' until the first events arrive.",
  "flow-unreachable": "Error state: the trade-flow source could not be reached (either /positions/minted or /redeemed errored). Both are polled every 6s.",
  // — Command strip + status bar + selectors —
  "indexer-status": "Health of the data indexer feeding every panel; OK means caught up to the chain. From GET /status: green OK / amber Sync / red Offline. The footer's authoritative health readout, same source as the live pill.",
  "lag": "How many seconds behind the chain the feed is; small is fresh, large means stale prices. data.max_time_lag_seconds from GET /status, raw integer seconds; shown in both the live pill and the footer.",
  "live-pill": "Whether fresh on-chain data is flowing now. Dot from GET /status: red=Offline (error), green=Live (OK), amber=Sync; the ping halo gates on the Tier-2 checkpoint push channel, distinct from the indexer poll.",
  "connect-wallet": "Connect a Sui wallet, or once connected your account (signs on-chain claims). Connected pill shows SuiNS name or truncateAddr (6/4) with a green dot; testnet; the write path for redeem_permissionless.",
  "market-selector": "Picker of BTC markets still open for trading. Lists oracles with derived status=active (activated, not settled), sorted by expiry; /oracles (~3.3k) is filtered client-side. Loading/'No market' states disable selection.",
  "utc-clock": "Current time in UTC, the universal trading clock so expiries and lag read unambiguously. ISO slice HH:MM:SS; renders '--:--:--' until hydrated. Markets settle on UTC timestamps.",
  "cmdk": "Keyboard shortcut (Cmd+K) that opens the quick command palette. Dispatches a 'deepskew:cmdk' window event the CommandPalette listens for; trigger hidden below sm.",
  "footer-links": "Footer chrome: external links to DeepBook Predict docs and the DeepBook X account, plus the 'redeploys mainnet day one' submission-credibility note. Not metrics.",
  "market-symbol": "The underlying asset of the market you're viewing, currently always Bitcoin. Predict's testnet lists only BTC rolling expiries, so the symbol is fixed while the expiry varies.",
  "network": "Which Sui network the terminal reads, testnet during the hackathon. SUI_NETWORK constant; Predict is testnet-only and redeploys to mainnet at launch.",
  "pill-tones": "Reusable colored capsule where color carries meaning: green=up, red=down/breach, cerulean=key/accent, amber=warn. Maps to semantic tokens --safe/--breach/--warn/--accent-brand; color = information, never decoration.",
  "wordmark": "Product name and home link; clicking returns to the desk root. DeepSkewMark glyph in cerulean, the authority signal of the desk.",
};
